todoproject/todoapp/urls.py
from . import views
from django.urls import path
app_name = 'todoapp'


urlpatterns = [
    path('', views.add, name='add'),
    path('delete/<int:task_id>/', views.delete, name='delete'),
    path('update/<int:task_id>/', views.update, name='update'),
    path('homelistview/', views.Tasklistview.as_view(), name='homelistview'),
    path('detailview/<int:pk>/', views.Taskdetailview.as_view(), name='detailview'),
    path('updateview/<int:pk>/', views.Taskupdateview.as_view(), name='updateview'),
    path('deleteview/<int:pk>/', views.Taskdeleteview.as_view(), name='deleteview'),
]

todoproject/todoproject/urls.py
from django.contrib import admin
from django.urls import path, include

from todoproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=250)
    priority = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return self.name

todoproject/todoapp/forms.py
from django import forms
from .models import Task


class TodoForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'priority', 'date']

todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView

from .models import Task
from .forms import TodoForm


# Create your views here.
class Tasklistview(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task_value'


class Taskdetailview(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task_value'


class Taskupdateview(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task_value'
    fields = ['name', 'priority', 'date']

    def get_success_url(self):
        return reverse_lazy('todoapp:detailview', kwargs={'pk': self.object.id})


class Taskdeleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:homelistview')


def add(request):
    task_value = Task.objects.all()
    if request.method == 'POST':
        name = request.POST.get('name')
        priority = request.POST.get('priority')
        date = request.POST.get('date')
        task = Task(name=name, priority=priority, date=date)
        task.save()
    return render(request, 'home.html', {'task_value': task_value})


def delete(request, task_id):
    task = Task.objects.get(id=task_id)
    if request.method == 'POST':
        task.delete()
        return redirect('/')


def update(request, task_id):
    task = Task.objects.get(id=task_id)
    form = TodoForm(request.POST or None, instance=task)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'task': task})

todoproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo App</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'script.js' %}"></script>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

todoproject/templates/delete.html
<form method="post">
    {% csrf_token %}
    <label>Are you Sure you Want to Delete?
        <input type="submit">
    </label>
</form>

todoproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="shadow card">
    <div class="card-body">
        <h5 class="card-title">{{task_value.name}}</h5>
        <p><b>{{task_value.priority}}</b></p>
        <p><b>{{task_value.date}}</b></p>
        <form method="post" action="{% url 'todoapp:deleteview' task_value.id %}">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
        </form><br>
        <a href="{% url 'todoapp:updateview' task_value.id %}"><button class="btn btn-success">Update</button></a>
    </div>
</div>
{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="p-3 shadow" >
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Task Name</label>
                    <input type="text" class="form-control" name="name" id="name" value="{{ task.name }}">
                </div>
                <div class="form-group">
                    <label style="margin-top: 10px" for="priority">Priority</label>
                    <input type="text" class="form-control" name="priority" id="priority" value="{{ task.priority }}">
                </div>
                <div class="form-group">
                    <label style="margin-top: 10px" for="date">Date</label>
                    <input type="date" class="form-control" name="date" id="date" value="{{ task.date}} }}">
                </div>
                <div style="text-align:center; margin-top:10px">
                    <input type="submit" class="btn btn-success">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="p-3 shadow" >
                {% csrf_token %}
                <div class="form-group">
                    <label for="name"></label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Task Name">
                </div>
                <div class="form-group">
                    <label style="margin-top: 10px" for="priority"></label>
                    <input type="text" class="form-control" id="priority" name="priority" placeholder="Enter your Priority">
                </div>
                <div class="form-group">
                    <label style="margin-top: 10px" for="date"></label>
                    <input type="date" class="form-control" id="date" name="date" placeholder="Enter Date">
                </div>
                <div style="text-align:center; margin-top:10px">
                    <input type="submit" class="btn btn-success">
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <h4>Task to be Completed</h4>
            {% for i in task_value %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <form method="post" action="{% url 'todoapp:delete' i.id %}" onsubmit="return myFunction(this)">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </form><br>
                    <a href="{% url 'todoapp:update' i.id %}"><button class="btn btn-success">Update</button></a>
                </div>
            </div><br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block body %}
<div class="card">
<div class="card-header">
    <div class="card-title">
        Task Update
    </div>
</div>
    <div class="card-body">
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Confirm</button>
        </form>
    </div>
</div>
{% endblock %}